server:
    port: 8000

spring:
    application:
        name: Inventory Management System
    datasource:
        url: jdbc:postgresql://localhost:5432/ims_db
        username: postgres
        password:
        driver-class-name: org.postgresql.Driver
    jpa:
        database: postgresql
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true

logging:
    file:
        name: src/main/resources/logs/application.log
    level:
        jpa: DEBUG
        org.springframework.security: DEBUG

